version: "3.8"

services:
  redis:
    image: redis:6.2

  demiroz_bank:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - SECRET_KEY=mysecret
      - ADMIN_USER=admin
      - ADMIN_PASSWORD_HASH=...
